//! Deterministic Markdown/HTML report rendering for `tempcheq report`.
//!
//! "Deterministic" means: given the same discovered actions, the output
//! bytes are identical on every run. In practice that means no wall-clock
//! timestamps, no HashMap iteration (Rust randomizes its hash seed per
//! process), and explicit sort keys everywhere findings are grouped or
//! listed — so two reports generated from the same commit, possibly on
//! different machines, diff as empty.

use crate::action::TemperatureState;
use crate::classify::{TaskClass, ALL_CLASSES};
use crate::report::Entry;
use std::cmp::Ordering;
use std::path::Path;

pub struct Summary {
    pub total: usize,
    pub controlled: usize,
    pub implicit: usize,
    pub inapplicable: usize,
    pub flagged: usize,
}

pub fn summarize(entries: &[Entry]) -> Summary {
    Summary {
        total: entries.len(),
        controlled: entries
            .iter()
            .filter(|e| matches!(e.action.temperature, TemperatureState::Explicit(_)))
            .count(),
        implicit: entries
            .iter()
            .filter(|e| matches!(e.action.temperature, TemperatureState::Implicit))
            .count(),
        inapplicable: entries
            .iter()
            .filter(|e| matches!(e.action.temperature, TemperatureState::Inapplicable))
            .count(),
        flagged: entries
            .iter()
            .filter(|e| e.rec.is_material_deviation(&e.action))
            .count(),
    }
}

/// Count per `TaskClass`, in `ALL_CLASSES` order (fixed, not hash order)
/// so chart row order never depends on discovery or process hash seed.
fn class_counts(entries: &[Entry]) -> Vec<(TaskClass, usize)> {
    ALL_CLASSES
        .iter()
        .map(|c| (*c, entries.iter().filter(|e| e.rec.class == *c).count()))
        .collect()
}

/// Flagged entries first (most severe deviation first), then everything
/// else in file/line order. Both groups break ties on (file, line) so the
/// ordering is fully determined by the findings themselves.
fn split_and_sort(entries: &[Entry]) -> (Vec<&Entry>, Vec<&Entry>) {
    let mut flagged: Vec<&Entry> = Vec::new();
    let mut rest: Vec<&Entry> = Vec::new();
    for e in entries {
        if e.rec.is_material_deviation(&e.action) {
            flagged.push(e);
        } else {
            rest.push(e);
        }
    }
    let file_line = |e: &&Entry| (e.action.file.clone(), e.action.line);
    flagged.sort_by(|a, b| {
        let da = a.rec.verdict(&a.action).map(|v| v.abs()).unwrap_or(0.0);
        let db = b.rec.verdict(&b.action).map(|v| v.abs()).unwrap_or(0.0);
        db.partial_cmp(&da)
            .unwrap_or(Ordering::Equal)
            .then_with(|| file_line(a).cmp(&file_line(b)))
    });
    rest.sort_by_key(file_line);
    (flagged, rest)
}

fn title_for(root: &Path, title: Option<&str>) -> String {
    title
        .map(|t| t.to_string())
        .unwrap_or_else(|| format!("TempCheq Report — {}", root.display()))
}

// ---------------------------------------------------------------------
// Markdown
// ---------------------------------------------------------------------

fn md_escape_cell(s: &str) -> String {
    s.replace('|', "\\|")
}

fn ascii_bar(count: usize, max: usize, width: usize) -> String {
    if max == 0 {
        return "░".repeat(width);
    }
    let filled = ((count as f64 / max as f64) * width as f64).round() as usize;
    let filled = filled.min(width);
    format!("{}{}", "█".repeat(filled), "░".repeat(width - filled))
}

pub fn render_markdown(root: &Path, entries: &[Entry], title: Option<&str>) -> String {
    let mut out = String::new();
    let s = summarize(entries);
    let (flagged, rest) = split_and_sort(entries);

    out.push_str(&format!("# {}\n\n", title_for(root, title)));
    out.push_str(&format!("Workspace: `{}`\n\n", root.display()));
    out.push_str(&format!("Generated by TempCheq v{}\n\n", env!("CARGO_PKG_VERSION")));

    out.push_str("## Summary\n\n");
    out.push_str("| Metric | Count |\n|---|---:|\n");
    out.push_str(&format!("| Inference actions found | {} |\n", s.total));
    out.push_str(&format!("| Temperature-controlled | {} |\n", s.controlled));
    out.push_str(&format!("| Implicit / default | {} |\n", s.implicit));
    out.push_str(&format!("| Temperature-inapplicable | {} |\n", s.inapplicable));
    out.push_str(&format!("| Flagged for review | {} |\n", s.flagged));
    out.push('\n');

    let breakdown_max = s.controlled.max(s.implicit).max(s.inapplicable).max(1);
    out.push_str("```\n");
    out.push_str(&format!(
        "controlled    {} {}\n",
        ascii_bar(s.controlled, breakdown_max, 30),
        s.controlled
    ));
    out.push_str(&format!(
        "implicit      {} {}\n",
        ascii_bar(s.implicit, breakdown_max, 30),
        s.implicit
    ));
    out.push_str(&format!(
        "inapplicable  {} {}\n",
        ascii_bar(s.inapplicable, breakdown_max, 30),
        s.inapplicable
    ));
    out.push_str("```\n\n");

    out.push_str("## Task classification\n\n```\n");
    let ccounts = class_counts(entries);
    let class_max = ccounts.iter().map(|(_, n)| *n).max().unwrap_or(0).max(1);
    for (class, n) in &ccounts {
        out.push_str(&format!(
            "{:<26}{} {}\n",
            class.label(),
            ascii_bar(*n, class_max, 24),
            n
        ));
    }
    out.push_str("```\n\n");

    out.push_str("## Flagged for review\n\n");
    if flagged.is_empty() {
        out.push_str("No actions materially outside their estimated optimum.\n\n");
    } else {
        out.push_str(
            "| Action | Location | Class | Current | Optimal | Deviation | Confidence |\n\
             |---|---|---|---:|---:|---:|---:|\n",
        );
        for e in &flagged {
            let verdict = e
                .rec
                .verdict(&e.action)
                .map(|v| format!("{v:+.2}"))
                .unwrap_or_else(|| "—".to_string());
            out.push_str(&format!(
                "| `{}` | {}:{} | {} | {} | {:.2} | {} | {:.2} |\n",
                md_escape_cell(&e.action.name),
                md_escape_cell(&e.action.file.display().to_string()),
                e.action.line,
                e.rec.class.label(),
                e.action.temperature.as_display(),
                e.rec.ideal,
                verdict,
                e.rec.confidence,
            ));
        }
        out.push('\n');
        out.push_str("### Reasoning\n\n");
        for e in &flagged {
            out.push_str(&format!(
                "**`{}`** ({}:{})\n\n",
                md_escape_cell(&e.action.name),
                e.action.file.display(),
                e.action.line
            ));
            for r in &e.rec.reasons {
                out.push_str(&format!("- {r}\n"));
            }
            out.push('\n');
        }
    }

    out.push_str("## All other actions\n\n");
    if rest.is_empty() {
        out.push_str("(none)\n\n");
    } else {
        out.push_str("| Action | Location | Kind | State | Class | Value |\n|---|---|---|---|---|---:|\n");
        for e in &rest {
            out.push_str(&format!(
                "| `{}` | {}:{} | {} | {} | {} | {} |\n",
                md_escape_cell(&e.action.name),
                md_escape_cell(&e.action.file.display().to_string()),
                e.action.line,
                e.action.source_kind.label(),
                temperature_state_label(&e.action.temperature),
                e.rec.class.label(),
                e.action.temperature.as_display(),
            ));
        }
        out.push('\n');
    }

    out.push_str("## Methodology\n\n");
    out.push_str(
        "'Optimal' values are heuristic priors from keyword-based task classification, not \
         measured outcomes — treat them as a starting point for review, not a verdict. Run \
         `tempcheq --benchmark` for a (simulated, clearly labeled) perturbation curve, or wire \
         in a real evaluation to ground these numbers empirically. Findings from broad markers \
         (e.g. any file containing a `\"model\":` key) are more prone to false positives than \
         explicit temperature assignments — cross-check low-confidence rows before acting.\n",
    );

    out
}

fn temperature_state_label(t: &TemperatureState) -> &'static str {
    match t {
        TemperatureState::Explicit(_) => "explicit",
        TemperatureState::Implicit => "implicit",
        TemperatureState::Inapplicable => "inapplicable",
    }
}

// ---------------------------------------------------------------------
// HTML
// ---------------------------------------------------------------------

fn esc_html(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}

/// A minimal, self-contained horizontal bar chart. No JS, no external
/// fonts/CDN — every value baked into plain SVG shapes and `<text>`.
fn svg_bar_chart(rows: &[(String, usize)], color: &str) -> String {
    let max = rows.iter().map(|(_, n)| *n).max().unwrap_or(0).max(1);
    let row_h = 26;
    let label_w = 190;
    let bar_max_w = 260;
    let width = label_w + bar_max_w + 60;
    let height = row_h * rows.len() + 10;

    let mut svg = format!(
        "<svg viewBox=\"0 0 {width} {height}\" width=\"100%\" height=\"{height}\" \
         xmlns=\"http://www.w3.org/2000/svg\" role=\"img\" aria-label=\"bar chart\">"
    );
    for (i, (label, count)) in rows.iter().enumerate() {
        let y = i * row_h;
        let bar_w = ((*count as f64 / max as f64) * bar_max_w as f64).round() as i64;
        let bar_w = bar_w.max(if *count > 0 { 2 } else { 0 });
        svg.push_str(&format!(
            "<text x=\"0\" y=\"{ty}\" font-size=\"12\" fill=\"#334155\">{label}</text>\
             <rect x=\"{label_w}\" y=\"{ry}\" width=\"{bar_w}\" height=\"14\" rx=\"2\" fill=\"{color}\"/>\
             <text x=\"{tx}\" y=\"{ty}\" font-size=\"12\" fill=\"#334155\">{count}</text>",
            ty = y + 12,
            ry = y + 2,
            tx = label_w + bar_w as usize + 8,
            label = esc_html(label),
        ));
    }
    svg.push_str("</svg>");
    svg
}

fn verdict_badge(verdict: Option<f32>) -> String {
    match verdict {
        None => "<span class=\"badge badge-neutral\">—</span>".to_string(),
        Some(v) => {
            let cls = if v.abs() > 0.3 {
                "badge-high"
            } else {
                "badge-med"
            };
            format!("<span class=\"badge {cls}\">{v:+.2}</span>")
        }
    }
}

pub fn render_html(root: &Path, entries: &[Entry], title: Option<&str>) -> String {
    let s = summarize(entries);
    let (flagged, rest) = split_and_sort(entries);
    let ccounts = class_counts(entries);
    let title_str = title_for(root, title);

    let breakdown_svg = svg_bar_chart(
        &[
            ("Temperature-controlled".to_string(), s.controlled),
            ("Implicit / default".to_string(), s.implicit),
            ("Inapplicable".to_string(), s.inapplicable),
        ],
        "#2563eb",
    );
    let class_svg = svg_bar_chart(
        &ccounts
            .iter()
            .map(|(c, n)| (c.label().to_string(), *n))
            .collect::<Vec<_>>(),
        "#7c3aed",
    );

    let mut flagged_rows = String::new();
    if flagged.is_empty() {
        flagged_rows
            .push_str("<tr><td colspan=\"7\" class=\"empty\">No actions materially outside their estimated optimum.</td></tr>");
    } else {
        for e in &flagged {
            flagged_rows.push_str(&format!(
                "<tr><td><code>{}</code></td><td>{}:{}</td><td>{}</td><td>{}</td>\
                 <td>{:.2}</td><td>{}</td><td>{:.2}</td></tr>",
                esc_html(&e.action.name),
                esc_html(&e.action.file.display().to_string()),
                e.action.line,
                esc_html(e.rec.class.label()),
                esc_html(&e.action.temperature.as_display()),
                e.rec.ideal,
                verdict_badge(e.rec.verdict(&e.action)),
                e.rec.confidence,
            ));
        }
    }

    let mut reasoning = String::new();
    for e in &flagged {
        reasoning.push_str(&format!(
            "<div class=\"reason-card\"><h3><code>{}</code> <span class=\"loc\">{}:{}</span></h3><ul>",
            esc_html(&e.action.name),
            esc_html(&e.action.file.display().to_string()),
            e.action.line
        ));
        for r in &e.rec.reasons {
            reasoning.push_str(&format!("<li>{}</li>", esc_html(r)));
        }
        reasoning.push_str("</ul></div>");
    }

    let mut rest_rows = String::new();
    if rest.is_empty() {
        rest_rows.push_str("<tr><td colspan=\"6\" class=\"empty\">(none)</td></tr>");
    } else {
        for e in &rest {
            rest_rows.push_str(&format!(
                "<tr><td><code>{}</code></td><td>{}:{}</td><td>{}</td><td>{}</td><td>{}</td><td>{}</td></tr>",
                esc_html(&e.action.name),
                esc_html(&e.action.file.display().to_string()),
                e.action.line,
                esc_html(e.action.source_kind.label()),
                esc_html(temperature_state_label(&e.action.temperature)),
                esc_html(e.rec.class.label()),
                esc_html(&e.action.temperature.as_display()),
            ));
        }
    }

    format!(
        r#"<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title_esc}</title>
<style>
{css}
</style>
</head>
<body>
<div class="container">
<header>
<h1>{title_esc}</h1>
<p class="workspace">Workspace: <code>{workspace}</code></p>
<p class="version">Generated by TempCheq v{version}</p>
</header>

<section class="summary-grid">
<div class="stat"><div class="stat-value">{total}</div><div class="stat-label">Actions found</div></div>
<div class="stat"><div class="stat-value">{controlled}</div><div class="stat-label">Temperature-controlled</div></div>
<div class="stat"><div class="stat-value">{implicit}</div><div class="stat-label">Implicit / default</div></div>
<div class="stat"><div class="stat-value">{inapplicable}</div><div class="stat-label">Inapplicable</div></div>
<div class="stat stat-flag"><div class="stat-value">{flagged_n}</div><div class="stat-label">Flagged for review</div></div>
</section>

<section>
<h2>Breakdown</h2>
<div class="chart">{breakdown_svg}</div>
</section>

<section>
<h2>Task classification</h2>
<div class="chart">{class_svg}</div>
</section>

<section>
<h2>Flagged for review</h2>
<div class="table-wrap">
<table>
<thead><tr><th>Action</th><th>Location</th><th>Class</th><th>Current</th><th>Optimal</th><th>Deviation</th><th>Confidence</th></tr></thead>
<tbody>{flagged_rows}</tbody>
</table>
</div>
{reasoning}
</section>

<section>
<h2>All other actions</h2>
<div class="table-wrap">
<table>
<thead><tr><th>Action</th><th>Location</th><th>Kind</th><th>State</th><th>Class</th><th>Value</th></tr></thead>
<tbody>{rest_rows}</tbody>
</table>
</div>
</section>

<section class="methodology">
<h2>Methodology</h2>
<p>"Optimal" values are heuristic priors from keyword-based task classification, not measured
outcomes — treat them as a starting point for review, not a verdict. Run
<code>tempcheq --benchmark</code> for a (simulated, clearly labeled) perturbation curve, or wire
in a real evaluation to ground these numbers empirically. Findings from broad markers (e.g. any
file containing a <code>"model":</code> key) are more prone to false positives than explicit
temperature assignments — cross-check low-confidence rows before acting.</p>
</section>

</div>
</body>
</html>
"#,
        title_esc = esc_html(&title_str),
        css = REPORT_CSS,
        workspace = esc_html(&root.display().to_string()),
        version = env!("CARGO_PKG_VERSION"),
        total = s.total,
        controlled = s.controlled,
        implicit = s.implicit,
        inapplicable = s.inapplicable,
        flagged_n = s.flagged,
        breakdown_svg = breakdown_svg,
        class_svg = class_svg,
        flagged_rows = flagged_rows,
        reasoning = reasoning,
        rest_rows = rest_rows,
    )
}

const REPORT_CSS: &str = r#"
:root {
  --bg: #f8fafc;
  --panel: #ffffff;
  --border: #e2e8f0;
  --text: #1e293b;
  --muted: #64748b;
  --accent: #2563eb;
  --flag-bg: #fef2f2;
  --flag-border: #fecaca;
}
* { box-sizing: border-box; }
body {
  margin: 0;
  background: var(--bg);
  color: var(--text);
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
  line-height: 1.5;
}
.container { max-width: 960px; margin: 0 auto; padding: 32px 20px 64px; }
header { border-bottom: 1px solid var(--border); padding-bottom: 16px; margin-bottom: 24px; }
h1 { font-size: 22px; margin: 0 0 8px; }
h2 { font-size: 16px; margin: 0 0 12px; color: var(--text); }
.workspace, .version { margin: 2px 0; color: var(--muted); font-size: 13px; }
code { background: #f1f5f9; border-radius: 3px; padding: 1px 5px; font-size: 0.9em; }
section { margin-bottom: 32px; }
.summary-grid { display: flex; flex-wrap: wrap; gap: 12px; }
.stat {
  flex: 1 1 140px;
  background: var(--panel);
  border: 1px solid var(--border);
  border-radius: 8px;
  padding: 14px 16px;
}
.stat-value { font-size: 24px; font-weight: 600; }
.stat-label { font-size: 12px; color: var(--muted); margin-top: 2px; }
.stat-flag { border-color: var(--flag-border); background: var(--flag-bg); }
.chart {
  background: var(--panel);
  border: 1px solid var(--border);
  border-radius: 8px;
  padding: 16px;
  overflow-x: auto;
}
.table-wrap {
  background: var(--panel);
  border: 1px solid var(--border);
  border-radius: 8px;
  overflow-x: auto;
}
table { border-collapse: collapse; width: 100%; font-size: 13px; }
th, td { text-align: left; padding: 8px 12px; border-bottom: 1px solid var(--border); white-space: nowrap; }
th { color: var(--muted); font-weight: 600; font-size: 12px; text-transform: uppercase; letter-spacing: 0.03em; }
tr:last-child td { border-bottom: none; }
td.empty { color: var(--muted); white-space: normal; }
.badge {
  display: inline-block;
  padding: 1px 8px;
  border-radius: 999px;
  font-size: 12px;
  font-weight: 600;
}
.badge-high { background: #fee2e2; color: #b91c1c; }
.badge-med { background: #fef3c7; color: #92400e; }
.badge-neutral { color: var(--muted); }
.reason-card {
  margin-top: 12px;
  padding: 12px 16px;
  background: var(--panel);
  border: 1px solid var(--border);
  border-radius: 8px;
}
.reason-card h3 { margin: 0 0 6px; font-size: 13px; }
.reason-card .loc { color: var(--muted); font-weight: normal; }
.reason-card ul { margin: 0; padding-left: 18px; font-size: 13px; color: var(--text); }
.methodology p { color: var(--muted); font-size: 13px; }
"#;
